#+DATE: 24 July 2021

#+TITLE: Local Variables & Functions

Previous: [[file:clbe-9.org][9. Basic Loops]]

Next: [[file:clbe-11.org][11. A Brief Detour - Code Formatting]]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

* Local Variables

LET and LET* are special operators that allow us to create local
variables that can only be accessed within their closures. LET binds
its variables in parallel such that you cannot refer to another
variable in the LET form when setting the value of another. LET* binds
its variables in sequentially, so thatyou can refer to the value of
any previously bound variables. This is useful when you want to assign
names to several intermediate steps in a long computation.

The LET form has the following syntax:

#+begin_src elisp

  (let ((var-1 value-1)
	...
	(var-n value-n))
    body-form*)

#+end_src

An example of LET* in use:

 #+begin_src lisp

   ;; Prints 10
   
   (let* ((x 5)
	  (y (+ x x)))
     (print y))

 #+end_src
 
As a general note on assignment, it is good programming style to avoid
changing the value of local variables after they have been set. This
makes our programs easier to follow as we do not need to track any
changes in the values of our local variables. Thus, we should only use
SETF on global variables and not alter variables created by LET and
LET* forms within their closures.

* Local Functions

Functions named by DEFUN are global functions that can be accessed
anywhere. We can define local functions through FLET and LABELS, which
are only accessible within their context. The scope of the functions
in a FLET form is limited to the body of the form and function
definitions are not visible to other functions defined by the FLET
form. LABELS is equivalent to FLET except that the scope of the
defined function names for LABELS encompasses the function definitions
themselves as well as the body. Practically this means LABELS allows
you to write recursive functions. The syntax of LABELS is:

#+begin_src lisp

  (labels ((fn-1 args-1 body-1)
	   ...
	   (fn-n args-n body-n))
    body-form*)

#+end_src

Functions defined within LABELS take a similar format to a DEFUN
form. Within the body of the LABELS form, function names matching
those defined by the LABELS refer to the locally defined functions
rather than any global functions with the same names. Below is an
example of a LABELS form that will return 12, the result of (+ 2 4 6),
where 2, 4 and 6 are the results of evaluating the three local
functions defined in the form.

#+begin_src lisp

  ;; Returns 12
  
  (labels ((first-function (x) (+ x x))
	   (second-function (y) (* y y))
	   (third-function (z) (first-function z)))
    (+ (first-function 1)
       (second-function 2)
       (third-function 3))) 

#+end_src
