#+DATE: 24 July 2021

#+TITLE: Further Reading

Previous: [[file:clbe-22.org][22. Lambda Expressions]]

Next: [[file:clbe-24.org][24. Appendix: Glossary]]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

We have come to the conclusion of this guide and I hope you found it
enjoyable and useful. There are quite a few topics that are not
covered in this guide, for example CLOS, the condition system and
the LOOP macro. Further details on these concepts and also other
concepts not covered in this guide can be found in the below
resources.

There is much more to learn in Lisp, our purpose today was simply to
help you get started in your journey. I really believe Lisp is a
beautiful and great language; I hope you do too.

Common Lisp the Language, 2nd Edition
http://www.cs.cmu.edu/Groups/AI/html/cltl/cltl2.html

Common Lisp: A Gentle Introduction to Symbolic Computing
http://www.cs.cmu.edu/%7Edst/LispBook/

Practical Common Lisp
http://www.gigamonkeys.com/book/

Common Lisp Cookbook
https://lispcookbook.github.io/cl-cookbook/

Many More Resources (including links to various textbooks) are
available on Reddit
https://www.reddit.com/r/lisp/

* Contact Information

Feel free to contact me for any feedback or comments for this guide.
If you find it useful, do please star the github repo where it is
uploaded, this helps me track the guide’s value and also
increases its credibility in the eyes of others.

Repo (please star it!)
https://github.com/ashok-khanna/common-lisp-by-example

My e-mail ashok.khanna@hotmail.com.
