#+DATE: 24 July 2021

#+TITLE: Global Functions

Previous: [[file:clbe-4.org][4. Input & Output]]

Next: [[file:clbe-6.org][6. Blocks]]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

In our earlier examples, we used some of Lisp’s built-in functions
such as + (for addition), READ (for reading input) and FORMAT (for
printing input). We will discuss how to define our own functions and
also introduce some common functions for manipulating numbers and
text.

Global functions are defined with DEFUN with the below syntax. The *
implies that multiple forms can be included in these parts. body-form
denotes the body of the function, which is wrapped in an implicit
BLOCK with the same name as function-name. Functions evaluate the
expressions of their bodies in order and return the value of the last
expression, unless exited earlier with RETURN-FROM. We will discuss
BLOCK and RETURN-FROM in the next section.


#+BEGIN_SRC elisp

  (defun function-name (parameter*)
    "Optional documentation string."
    body-form*)
  
#+END_SRC

An example of a function that multiplies the sum of two numbers by 10
is below, together with its function call.

#+begin_src lisp

  (defun multiply-sum-by-10 (x y)
    "Returns the sum of two numbers multiplied by 10"
    (* 10 (+ x y)))

  ;; Returns 150

  (multiply-sum-by-10 5 10)

#+end_src

* Numerical Functions

Some of Lisp’s most basic functions are for arithmetic, e.g. (+ 3 3.0)
for addition, (- 3 3.0) for subtraction, (* 3 3.0) for multiplication
and (/ 3 3.0) for division. Numerical functions disregard type, i.e. 3
and 3.0 are treated as equal and we can complete arithmetic operations
on disparate numerical types such as integer and floating point
numbers without error. We can compare numbers with the below
functions. With two arguments, they perform the usual arithmetic
comparison tests. With three or more arguments, they are useful for
range checks.

= /= (not) < > <= >=


Below are examples of these functions.

#+begin_src lisp

  (defparameter x 5)
  
  (defparameter y 4)

  
  ;; Returns true as x between 0 and 5 inclusive
  
  (<= 0 x 5)

  
  ;; Returns false as x not between 0 and 5 exclusive
  
  (< 0 x 5)

  
  ;; Returns false as x > y

  (< 0 x y 6)

  
  ;; Returns true

  (< 0 y x 6)

#+end_src

Two other useful functions are MAX and MIN. Finally, we can use ABS to
return the absolute value of one number.

* Text Functions

We will now cover some useful functions for joining strings
(CONCATENATE), retrieving their length (LENGTH), extracting a portion
of a string (SUBSEQ) and searching within a string (SEARCH). The
FORMAT function that we discussed earlier is very useful for
constructing strings made up of smaller strings that we supply into
the FORMAT function as arguments.

Below are examples of joining and searching within a string and
retrieving its length in characters. SEARCH will return the starting
point of the term searched or NIL if not found.

#+begin_src lisp

  (concatenate 'string "Hello, " "world" ". Today is good.")


  ;; Returns 6

  (length "Common")
  

  (search "term" "the term is search within this string")

#+end_src

SUBSEQ retrieves a portion of a string starting from a supplied
starting position (indexed from 0) and an optional ending position
(which is not included in the string):

#+begin_src lisp

  ;; Returns "Lisp"
  
  (subseq "Common Lisp" 7 11)

#+end_src

Below are comparison functions for strings. Replace STRING with CHAR
in the below to get the equivalent character comparison functions.

| Case Sensitive | Case Insensitive    |
|----------------+---------------------|
| STRING=        | STRING-EQUAL        |
| STRING/=       | STRING-NOT-EQUAL    |
| STRING<        | STRING-LESSP        |
| STRING<=       | STRING-NOT-GREATERP |
| STRING>        | STRING-GREATERP     |
| STRING>=       | STRING-NOT-LESSP    |


Note on usage: A string A is less than a string B if in the first
position in which they differ the character of A is less than the
corresponding character of B according to the function CHAR<, or if
string a is a proper prefix of string B (of shorter length and
matching in all the characters of A).
