#+DATE: 2 September 2021
#+OPTIONS: html-postamble:nil

#+TITLE: Ashok on the Web

Thank you for visiting my website. I like to write about Computer Science and Web
Design. In addition, I like to save down valuable resources I find online, which
you may also find useful. Thank you for your time and [[file:mailto:email@ashok.jp][contact me if anything sparks your interest]].


* Articles

I write about Computer Science and Design in the [[file:articles.org][articles section of my website]].
The four most recent articles are listed below.

1. [[file:https://ashok-khanna.medium.com/introduction-to-dired-mode-91cecd3a06ff][Introduction to Dired Mode]] (August 23, 2021)

2. [[file:https://ashok-khanna.medium.com/continuations-in-common-lisp-1911cb413a03][Continuations in Common Lisp]] (August 17, 2021)

3. [[file:https://ashok-khanna.medium.com/introduction-to-asdf-d25efe2780c2][Introduction to ASDF]] (August 13, 2021)

4. [[file:https://ashok-khanna.medium.com/persistent-in-memory-data-storage-in-common-lisp-b-k-n-r-37f8ae76042f][Persistent in Memory Data Storage in Common Lisp]] (June 23, 2021)



* Resources

I save down useful papers, free books and weblinks in the [[file:resources.org][resources section of my website]].
Two useful resources are below.

1. [[file:https://hyperspec.ashok.jp][Common Lisp HyperSpec]] - A mirror of the Common Lisp HyperSpec, as kindly
   made available by [[file:https//www.lispworks.com][LispWorks]] and the acclaimed [[file:http://www.nhplace.com][Kent Pitman]].

2. [[file:https://lisp.ashok.jp][Common Lisp, the Language 2nd Edition]] - A mirror of the venerable reference textbook
   for Common Lisp, written by the acclaimed [[file:http://www.nhplace.com][Guy Steele]]. 



* GitHub & Medium

I [[file:https://ashok-khanna.medium.com][also blog Medium]], where I have roughly 1,000 readers per month. I tend
to write first on Medium and later transfer a copy here. Medium
helps me gain visibility and some of my articles are top ranked in Google 
searches for their topics.

I also share some of my open source projects on [[file:https://github.com/ashok-khanna][GitHub]]. A lot of my work
is private, but I try to contribute to open source and the free software
movement when I have time. Some of my contributions include:

1. [[file:https://github.com/ashok-khanna/lisp-notes][The Common Lisp Cheat Sheet]] - My ongoing introductory guide to Common Lisp,
   which is now featured on the Reddit Sidebar for r/lisp. 

2. [[file:https://pdf.math.dev][Beautiful PDFs from HTML]] - My tutorial on using Paged.Js to produce paginated
   media from HTML. It has been read over 20,000 times and currently has over 250
   stars on Github. It is a good read for anybody looking to automate PDF report
   generation by taking advantage of Chrome's rendering engine (preferably in a
   headless setup). The accompanying Hacker News discussion can be found [[file:https://news.ycombinator.com/item?id=26691626][here]]
   (note that I changed website domains, so the web link on HN no longer works).

3. [[file:https://apps.apple.com/us/app/rpn-30/id1451413517][RPN 30]] - My highly rated Reverse Polish Notation calculator for iPhones.
   It has over 15,000 downloads and counting, together with a 4.8/5 star rating
   on the Apple App Store with roughly 50 reviews to date. A sample of its reviews
   [[file:/rpn30-reviews.html][can be found here]]. The full source code of this calculator is [[file:https://github.com/ashok-khanna/RPN-31][available here]],
   and is a useful example for those trying to learn Swift & SwiftUI.

4. [[file:https://github.com/ashok-khanna/math-hydras][Math Hydras]] - My keybindings for inserting greek letters and mathematical symbols
   quickly in Emacs.

5. [[file: https://ashok-khanna.medium.com/lisp-the-web-4c00c88d11f9][Lisp & the Web]] - A detailed step through for creating cloud-based web applications
   through Common Lisp and Google Compute Engine. It has been read over 10,000 times.


* Contact

You may contact me at [[file:mailto:email@ashok.jp][email@ashok.jp]]. If you like what I do and would
like to work together on some project, I would love to hear what you have in
mind. You can also reach out to me for any technical writing assignments.
