#+DATE: 2 September 2021
#+OPTIONS: html-postamble:nil

#+TITLE: Resources

Below are a collection of useful resources I found online. In many cases,
I will link directly to their websites, but also append an internal link for
an archived version that I store on this website to preserve these high quality
resources in the event there are taken down in the future.

All the resources below were freely available online at the time I found them.
If you are the author of any of the below and would like your resource removed
from the below listing, please kindly let me know and I will do so immediately. My aim
is to purely provide a platform to highlight the below resources, and not to profit
or otherwise benefit from any of them in any way.


* Common Lisp

1. [[file:https://hyperspec.ashok.jp][Common Lisp HyperSpec]] - A mirror of the Common Lisp HyperSpec, as kindly
   made available by [[file:https//www.lispworks.com][LispWorks]] and the acclaimed [[file:http://www.nhplace.com][Kent Pitman]].

2. [[file:https://lisp.ashok.jp][Common Lisp, the Language 2nd Edition]] - A mirror of the venerable reference textbook
   for Common Lisp, written by the acclaimed [[file:http://www.nhplace.com][Guy Steele]]. 

